#!/usr/bin/env bash

blue='\033[0;34m'
green='\033[0;32m'
nc='\033[0m'

# To do list, criar funções:
# 1 storage account
# 2 config de variaveis de backend
# 3 para iniciar o terraform
# 4 função pra destruir/limpar ambiente
# 5 função de git push

if [ -z "$@" ]; then
    echo -e "o que você que executar?\n
    1- Git commit: ./run git-commit
    2- Terraform: ./run tf
    3- Terraform remote tfstate: ./run tfstate
    4- Limpar deploy: ./run clear"
    exit 0

else

    tf() {
        dir="-chdir=terraform/env"
        echo -e "Importando provider:"
        terraform $dir init

        if [ $? -eq 0 ]; then
            echo -e "\nValidate Status: "
            terraform $dir validate

            if [ $? -eq 0 ]; then
                echo -e "\nPlan Status: "
                terraform $dir plan -out=tfplan

                read -p "Press enter to start Apply or CTRL+C to finish the script."

                if [ $? -eq 0 ]; then
                    terraform $dir apply tfplan
                    exit 0
                fi
            fi
        fi
    }

    git-commit() {
        branch=$(git symbolic-ref HEAD | sed -e "s/^refs\/heads\///")

        git add .

        printf "${blue}Mensagem do commit: ${green}"
        read commitMessage

        git commit -m "$commitMessage" >/dev/null

        echo -e "\n${blue}Push:${green}"
        git push origin ${branch}
    }
fi

"$@"
